### ISSUE TITLE
Wrong relative path for loading.gif in assets/css/plugins/lightbox.min.css

### ISSUE THREAD

**Issue by trollwookiee** [app-generator/django-dashboard-gradient-pro#2]
remote:        whitenoise.storage.MissingFileError: The file 'assets/css/images/loading.gif' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f7f8882d550>.
remote:        The CSS file 'assets/css/plugins/lightbox.min.css' references a file which could not be found:
remote:          assets/css/images/loading.gif
remote:        Please check the URL references in this CSS file, particularly any
remote:        relative paths which might be pointing to the wrong location.
remote:
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.

**Comment by trollwookiee** [comment]
same for prev.png, next.png, close.png

**Comment by trollwookiee** [comment]
core/static/assets/css/plugins/lightbox.min.css needs to be modified to refer to:
**../**../images/loading.gif instead of ../images/loading.gif

**Comment by app-generator** [comment]
Hello @trollwookiee, 

Issues patched in [commit](https://github.com/app-generator/priv-django-dashboard-gradient-pro/commit/765200a81d2231e19ffa7b07eadc59b86c380249) 

Please update.
